# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f37452746d0bfbfa62011768762e589bb7c1a8889d0ae6b6679f5a3ce327d50a10cd6bb2de743e196ed82a5b38b3fc8fa6711143f98836a68c76e2989b5f8cc

test:
  secret_key_base: 8bd26ff590819ccff7b230725b03a45313fdb15654488bfbf7c4f50ec14153cd62971e9dbd25b97de24e2e5217de1e711a011c1a44e1e67caada6551e9254762

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
